#!/usr/bin/env ruby

require 'erb'
require 'fileutils'
require 'optparse'

$options = {
}

simple_template = "((split <%= split %>) (mshs <%= mshs %>))"
hidden_object_template = <<END
((split <%= split %>) (mshs <%= mshs %>) (preallocations ((sizes (2097152)) (low 10485760) (high 140733191290880)))
(hole_descrs_by_pos ((AbsPosAndSortSize 0 2
  (((name Large) (behavior AllocHigh) (min 69816839827456)
      (max 140733191286784))
         ((name Small) (behavior AllocHigh) (min 4096) (max 70366595649536))))
          (BeforeStack
            ((name B) (behavior AllocLow) (min 1073741824) (max 1103806595072)))
             (EndOfUserspace ((name C) (behavior AllocLow) (min 4096) (max 4294967296))))))
END

templates = {
  "simple" => ERB.new(simple_template),
  "hidden-object" => ERB.new(hidden_object_template),
}

def pute(s)
  $stderr.puts(s)
end

OptionParser.new { |opts|
  opts.banner = "Usage: #{$0} [options]"
  opts.on("-t", "--template=NAME", "Which template to use") { |t|
    $options[:template] = t
  }
  opts.on("-o", "--outdir=PATH", "Where to write the templates") { |p|
    $options[:outdir] = p
  }
}.parse!

if $options[:outdir].nil?
  pute("No outdir specified")
  exit(2)
end

if $options[:template].nil?
  pute("No template specified")
  exit(2)
end

template = templates[$options[:template]]

if template.nil?
  pute("No such template: '#{$options[:template]}'")
  exit(2)
end

mshss = [2101248, 4194304, 6291456, 8388608, 10485760, 20971520, 41943040]
splits = [2, 4, 6, 8, 10, 12, 14, 16, 20, 24, 28, 32, 48, 64]

FileUtils.mkdir_p($options[:outdir])

mshss.each { |mshs|
  splits.each { |split|
    data = template.result(binding)
    File.open("#{$options[:outdir]}/split_#{split}_mshs_#{mshs}.sexp", "w") { |o|
      o.puts(data)
      o.flush
    }
  }
}

